### ISSUE TITLE
blog post on nglviewer and MDAnalysis

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#10]
@dotsdl showed me very cool stuff... he really should show you, too

**Comment by kain88-de** [comment]
I've seen the repository and that they seem to have full support for MDAnalysis now. A  blog post about it would be very nice indeed.

**Comment by dotsdl** [comment]
Working on one now. Will have it up by end of week.

**Comment by kain88-de** [comment]
awesome thanks

**Comment by jandom** [comment]
@dotsdl missed a deadline there haven't we? let's put a bird on it 

```
                      ___  
                  _,-' ______
                .'  .-'  ____7
               /   /   ___7
             _|   /  ___7
           >(')\ | ___7     jgs
             \\/     \_______
             '        _======>
             `'----\\`        
```
