### ISSUE TITLE
add BioEn to "used by" page

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#103]
@katrinr said:

> saw that you started a list with computational tools using MDAnalysis. We also use it and have the code available on 
> 
> https://github.com/bio-phys/BioEn
> 
> and MDAnalysis was so helpful, that we also just published Nature Communications paper. 

Add to https://www.mdanalysis.org/pages/used-by/

**Comment by katrinr** [comment]
This is the publication:
https://pubs.acs.org/doi/10.1021/acs.jpclett.8b02439

@article{Reichel2018,
  title={Precision DEER distances from spin-label ensemble refinement},
  author={Reichel, Katrin and Stelzl, Lukas S and K\"{o}finger, J\"{u}rgen and Hummer, Gerhard},
  journal={J. Phys. Chem. Lett.},
  volume={9},
  number={19},
  pages={5748--5752},
  year={2018},
  publisher={ACS Publications}
}
