### ISSUE TITLE
blog post introducing GSoC 2019 student Ninad Bhat

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#105]
Create a blog post introducing our GSoC 2019 student Ninad Bhat
- [x] link to his blog https://ninadbhat.github.io/
- [x] link to GSoC participants page
- [x] picture of @NinadBhat 
- [x] brief bio of @NinadBhat 
- [x] summary of his project
- [x] mentors @jbarnoud @richardjgowers @micaela-matta @orbeckst 

See https://github.com/MDAnalysis/MDAnalysis.github.io/blob/master/_posts/2018-04-26-gsoc-students.md as example.

**Comment by orbeckst** [comment]
@NinadBhat could you have a look at last years intro blog post [GSoC 2018 students](https://www.mdanalysis.org/2018/04/26/gsoc-students/) and provide us with the following 
- short biography (you can reveal as much or as little as you like about your professional/academic life)
- portrait picture (link or attach – we can also use the one from your blog)
- short summary of your project (start by copy & paste your GSoC abstract and add if necessary)

This post will be shorter than your own post. The idea is to introduce you and your project to the community and send them to your blog to learn more.

**Comment by orbeckst** [comment]
@NinadBhat you can directly edit the markdown file in the PR #106 – GitHub will automatically create a PR for you.

**Comment by orbeckst** [comment]
Thanks @NinadBhat !

Do you have a twitter handle that we can include in a tweet?

**Comment by NinadBhat** [comment]
@orbeckst I do not use twitter.

**Comment by orbeckst** [comment]
Ok, thanks. Just checking. 

--
Oliver Beckstein
email: orbeckst@gmail.com
