### ISSUE TITLE
update governance section

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#113]
The section https://www.mdanalysis.org/about/#governance states how we operate. The MDAnalysis Core Developers agree to the following changes

## Changes
We use the designation "MDAnalysis Core Developers" consistently and change the decision finding to simple majority.

1. ~"Project leadership is currently provided by a subset of contributors, the Core Developers (@MDAnalysis/coredevs)"~ -> Project leadership is provided by a subset of contributors, the *MDAnalysis Core Developers* (@MDAnalysis/coredevs)
2. ~*In general, all project decisions are made through consensus among the Core Developers.*~ -> All decisions by the MDAnalysis Core Developers are made by simple majority.
3. ~New Core Developers are elected with a simple majority of current Core Developers.~ -> New MDAnalysis Core Developers are elected with a simple majority of current MDAnalysis Core Developers.
4. ~A rotating subset of three Core Developers is tasked to respond to and to investigate Code of Conduct violations.~ -> A rotating subset of three MDAnalysis Core Developers is tasked to respond to and to investigate Code of Conduct violations.

## Vote
@MDAnalysis/coredevs : please use the 👍 or 👎 to formally vote on this change.

(Note: if you want to time-stamp your vote, additionally comment below.)

**Comment by orbeckst** [comment]
I agree with all changes 1–4. 👍

**Comment by kain88-de** [comment]
👍

**Comment by jbarnoud** [comment]
:+1:

**Comment by seb-buch** [comment]
👍
Not sure I still can be defined as a core dev since I have not contributed for some time... but my resolution for this year is to give more attention and time to things I like to do and mda is one of them!

**Comment by zemanj** [comment]
:+1:

**Comment by jandom** [comment]
Sounds good!

**Comment by orbeckst** [comment]
Please review & merge PR #114.
