### ISSUE TITLE
Social Media Buttons

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/MDAnalysis.github.io#12]
It would be nice to have some quick-access social media buttons. I would like them grouped either at the top or bottom of the navigation bar.
- RSS
- Twitter
- Mailing Lists
- PyPi ?

Do we have other social media outlets?

**Comment by orbeckst** [comment]
Didn't you have examples for some of these? I just can't remember where you posted them.

**Comment by orbeckst** [comment]
I don't think I have the energy/time to figure that one out. I'll close it for now... if someone feels strongly about it, please re-open.
