### ISSUE TITLE
add taurenmd to used-by

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#125]
Add @joaomcteixeira 's [taurenmd](https://github.com/joaomcteixeira/taurenmd) to the https://github.com/MDAnalysis/MDAnalysis.github.io/blob/master/pages/used-by.md page.

(See discussion https://github.com/MDAnalysis/mdanalysis/issues/2377#issuecomment-597129652)

**Comment by joaomcteixeira** [comment]
Done in #126 .

I deeply appreciate your consideration!
