### ISSUE TITLE
blog post introducing GSoC 2020 students

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#127]
Create a blog post introducing our GSoC 2020 students @hmacdope @cbouy @yuxuanzhuang 
- [x] link to their blogs 
- [x] link to GSoC participants page
- [x] pictures 
- [x] brief bios 
- [x] summary of projects
- [x] explicitly include mentors (see @MDAnalysis/gsoc-mentors for assignments)
- [ ] tweet

See https://github.com/MDAnalysis/MDAnalysis.github.io/blob/master/_posts/2018-04-26-gsoc-students.md as example.

**Comment by orbeckst** [comment]
GSoC page https://summerofcode.withgoogle.com/organizations/4891814374408192/#5116604104310784

**Comment by orbeckst** [comment]
Draft for the tweet:

> We are excited to introduce our three #gsoc 2020 students and their projects https://www.mdanalysis.org/blog/2020/05/20/gsoc-students/ : Yuxuan Zhuang (parallelization),  @hugomacdermott (TNG format in collaboration with @GMX_TWEET), @cedricbouysset (#RDKit and MDAnalysis).

- [ ] Check that the link works before tweeting!
- [ ] Check the character limit. If there's more available, say more nice things.

**Comment by IAlibay** [comment]
> Check the character limit. If there's more available, say more nice things.

I believe you have 41 characters left on that tweet. 

Couple of suggestions:
1) Might want to switch #RDKit for @RDKit_org?
2) I think `parallelization` and `TNG format` are self-explanatory, but the RDKit one is a bit ambigious, maybe "MDAnalysis interface to @RDKit_org"?

**Comment by IAlibay** [comment]
Just re-opening this since the tweet hasn't been done.

**Comment by orbeckst** [comment]
Done https://twitter.com/mdanalysis/status/1263629230505484288
