### ISSUE TITLE
1.x blog post

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#130]
Need to announce 1.0.
- [x] 1.0.1 patch release... https://github.com/MDAnalysis/mdanalysis/issues/2768 (so that people don't complain about 1.0.0 right away....)
- [ ] blog
- [ ] tweet
- [ ] .... whatever else

**Comment by orbeckst** [comment]
Topics
- [roadmap](https://www.mdanalysis.org/2019/11/06/roadmap/) python 2.7/3.x
- stable release (all functionality from 0.20.1 except anything deprecated long ago such as instant selectors and flags), linux/macOS/windows
- User Guide
- enhancements
  - new analysis modules
  - interoperability (converter framework)
  - on the fly transformations
- fixes
- contributors, GSoC, NumFOCUS

What else?

**Comment by IAlibay** [comment]
support improvements:
  - Windows 32 bit support

for enhancements:
  - Support for multiple wildcards in selections
  - New readers: Chemfiles & Parmed (I guess it's under interoperatbility), FHI-AIMS, ITParser, 2020 TPR files
  - New ProgressBar

major changes in the way people use MDAnalysis:
  - Deprecated passing of start/stop/step to __init__ has been removed
  - `select` is now the standard selection keyword across analysis methods
  - Passing timesteps to writers (which was supported by many writers) is now deprecated and will be removed in 2.0.

**Comment by IAlibay** [comment]
I'm bumping this up to 1.x since we never did a 1.0 blog post (as far as I'm aware) and we've now completed the 1.x branch with 1.1.1.
