### ISSUE TITLE
remove Google Analytics

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#131]
As part of the discussion on privacy #129 we are also tending towards removing  intrusive Google Analytics tracking. We still would like to have an idea of number of visitors. 

One less intrusive suggestion was https://www.goatcounter.com/ but someone needs to look into what is necessary there.

- [x] remove GA from main site https://github.com/MDAnalysis/MDAnalysis.github.io/blob/dce751c6dd00698155bae2c28d9d7d6ffc833db8/_includes/head.html#L44-L52
- [x] check generated docs if we use GA there and remove
- [x] add goatcounter
- [x] share login details in NF teamdrive

**Comment by orbeckst** [comment]
I registered for goatcounter ; stats at https://mdanalysis.goatcounter.com/

Need to add
```html
<script data-goatcounter="https://mdanalysis.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
```

**Comment by orbeckst** [comment]
It does not look as if we explicitly tracked our sphinx-generated docs: We would have used something like [sphinxcontrib-googleanalytics](https://pypi.org/project/sphinxcontrib-googleanalytics/), which we don't use, and I also can't find the tracking ID UA-18574059-3 embedded anywhere else.

**Comment by kain88-de** [comment]
FYI: Linux News Weekly recently had an article on Google Analytics alternatives. One suggestion there is goatcounter


https://lwn.net/Articles/823525/rss

**Comment by orbeckst** [comment]
GoatCounter does not have slick fine grained access controls for managers. It looks as if the simplest solution is to share the login details. Let me know if you want them right away. I will also add a document to the shared NumFOCUS team drive.

**Comment by kain88-de** [comment]
The developer is not a Lawyer. I would rather like to err on the side of
caution and include the gdpr note.

Best Max.

**Comment by orbeckst** [comment]
There's a simple js-based example at https://www.goatcounter.com/code#consent-notice.

**Comment by kain88-de** [comment]
Follooup article from lwn: https://lwn.net/SubscriberLink/824294/c2837d5db64c820e/

**Comment by orbeckst** [comment]
I‘ll merge this PR and open a new one for a GDPR notice.
