### ISSUE TITLE
page counting for docs

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#134]
The data collected on https://mdanalysis.goatcounter.com/ (see #131) is pretty basic and shows which pages are accessed. Question for @MDAnalysis/coredevs :

Should we collect the same data for 
- MDAnalysis docs
- User Guide
- other packages (PMDA, gridcount, ...)

We just need to find a way to insert the js snippet before the `</body>` tag.

However, in this case we should also include a link to the Privacy Policy #129.

**Comment by tylerjereddy** [comment]
Lots of visitors on Windows machines!

If the process isn't too complicated I suppose the justification of grant-related metrics is appropriate.

**Comment by orbeckst** [comment]
Works with a simple `layout.html` [template](https://www.sphinx-doc.org/en/master/templating.html), similar to how [use sphinx with Google Analytics (FAQ)](https://www.sphinx-doc.org/en/master/faq.html#using-sphinx-with).

See https://github.com/MDAnalysis/GridDataFormats/commit/ba563d9b94499b2406fdd0f516867dea5dd350ce

**Comment by orbeckst** [comment]
https://stackoverflow.com/a/5585354 (comment) says that for RTD theme one needs
```
{% extends '!footer.html' %} {% block extrafooter %} <!-- your html code here --> {% endblock %}
```

**Comment by orbeckst** [comment]
All our active pages are now GoatCounterified (they also have a shiny new doc style and a link to the privacy notice).

See https://mdanalysis.goatcounter.com/ for what the favorite pages are (just give the newcomers like the User Guide a few days to catch up).
