### ISSUE TITLE
Change theme to match docs / userguide and window size

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/MDAnalysis.github.io#135]
- [x] As @orbeckst [points out](https://github.com/MDAnalysis/mdanalysis/issues/2800#issuecomment-650486272), the [website theme](https://www.mdanalysis.org/) doesn't match that of the [docs](https://docs.mdanalysis.org/2.0.0-dev0/) and [user guide](https://userguide.mdanalysis.org/) (specifically a grey sidebar vs the black one).
- [ ] Additionally, when the window is too small for the website, the view is anchored to the sidebar bottom and I can't scroll up or down (in Safari, Firefox, and Chrome). Changing this to something scrollable would be nice.

<img width="357" alt="Screenshot 2020-06-27 at 9 11 23 PM" src="https://user-images.githubusercontent.com/31115101/85920937-8354f680-b8bb-11ea-9b70-b55f2a61fb8d.png">

**Comment by orbeckst** [comment]
A first step would be just to change the color scheme.

The responsivity is probably a bit more complicated and might be tied to the Jekyll theme that we are using. 

(For what it;s worth: i have no problem looking at the site on a small phone. The menu is just taking up the top part of the screen and I can scroll down into the content part.)

**Comment by orbeckst** [comment]
Additionally, we should change the theme for all the other docs...

**Comment by orbeckst** [comment]
@lilyminium do you want to take a crack at changing the colors of the main site? 

Everything else is transitioned to the User Guide theme.

**Comment by orbeckst** [comment]
The anchored menu is a bit annoying in combination with the floating search box, which gets cut off so that only the first two or so results are visible.

**Comment by orbeckst** [comment]
Do you still have the window resizing issue? When I make my firefox window small, I can scroll up and down and it looks like my mobile phone.

**Comment by orbeckst** [comment]
I am closing this issue. If window size/scrolling comes up again, let's open a new issue.
