### ISSUE TITLE
run local version of website

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/MDAnalysis.github.io#14]
We need to update the guide how to run the webserver locally for people who have no idea about jekyll. The github documentation we link against doesn't help at all.

right now I have the following list of commands

```bash
gem install jekyll --user-install
bundle install
bundle exec jekyll serve
```

But this still doesn't work because I'm missing some javescript environment.

**Comment by orbeckst** [comment]
This worked for me (using Macports).

**Comment by orbeckst** [comment]
What is the error that you get?

**Comment by dotsdl** [comment]
I usually just do `jekyll serve`, and that works. I'm not sure what role `bundle` plays in this, but I imagine it solves a similar problem to `conda` (perhaps without precompiled binaries) in the Ruby world, while `gem` is more basic. I'll elaborate on what I did to set up my environment.

On an Arch Linux box:
1. installed ruby with `pacman -S ruby`.
2. installed necessary gem with `gem install jekyll`, which puts the installed ruby package in `~/.gem/ruby/2.3.0/`.
3. added `~/.gem/ruby.2.3.0/bin` to my path, which is where the `jekyll` executable lives.
4. ran `jekyll serve` in our website repository. Noted missing plugin packages needed for generation of site.
5. Ran `gem install <packagename>` for each package `jekyll serve` complained about until it complained no more.

**Comment by kain88-de** [comment]
@dotsdl I used bundle because that is what the github documentation suggests for installing jekyll. 

This is the complete error I get.

```
/home/max/.gem/ruby/gems/execjs-2.6.0/lib/execjs/runtimes.rb:48:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
	from /home/max/.gem/ruby/gems/execjs-2.6.0/lib/execjs.rb:5:in `<module:ExecJS>'
	from /home/max/.gem/ruby/gems/execjs-2.6.0/lib/execjs.rb:4:in `<top (required)>'
	from /home/max/.gem/ruby/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `require'
	from /home/max/.gem/ruby/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `<top (required)>'
	from /home/max/.gem/ruby/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `require'
	from /home/max/.gem/ruby/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `<top (required)>'
	from /home/max/.gem/ruby/gems/jekyll-coffeescript-1.0.1/lib/jekyll-coffeescript.rb:2:in `require'
	from /home/max/.gem/ruby/gems/jekyll-coffeescript-1.0.1/lib/jekyll-coffeescript.rb:2:in `<top (required)>'
	from /home/max/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/deprecator.rb:46:in `require'
	from /home/max/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/deprecator.rb:46:in `block in gracefully_require'
	from /home/max/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/deprecator.rb:44:in `each'
	from /home/max/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/deprecator.rb:44:in `gracefully_require'
	from /home/max/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll.rb:141:in `<top (required)>'
	from /home/max/.gem/ruby/gems/jekyll-2.4.0/bin/jekyll:6:in `require'
	from /home/max/.gem/ruby/gems/jekyll-2.4.0/bin/jekyll:6:in `<top (required)>'
	from /home/max/bin/jekyll:23:in `load'
	from /home/max/bin/jekyll:23:in `<main>'

```

**Comment by kain88-de** [comment]
https://github.com/sstephenson/execjs/issues/154

following this I found that I have to install `nodejs` as well. After that it works
