### ISSUE TITLE
ensure sitemap validity

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#143]
As part of debugging #142 (see also https://github.com/algolia/docsearch-configs/issues/2103 ) we need to validate all our sitemaps

* protocol (format): https://www.sitemaps.org/protocol.html
* validator (there are many), e.g. https://www.websiteplanet.com/webtools/sitemap-validator and https://www.xml-sitemaps.com/validate-xml-sitemap.html

EDIT: the sitemaps were tested with [Website Planet sitemap-validator](https://www.websiteplanet.com/webtools/sitemap-validator) and [xml-sitemaps.com validator](https://www.xml-sitemaps.com/validate-xml-sitemap.html). The former always gives the same *2 errors* (linked below), the latter considers all our sitemap XML files valid:
- [x] https://www.mdanalysis.org/sitemapindex.xml – [validated](https://www.websiteplanet.com/webtools/sitemap-validator/?page=https://www.mdanalysis.org/sitemapindex.xml)
- [x] https://docs.mdanalysis.org/1.0.0/sitemap.xml – [2 errors](https://www.websiteplanet.com/webtools/sitemap-validator/?page=https://docs.mdanalysis.org/1.0.0/sitemap.xml), [valid](https://www.xml-sitemaps.com/validate-xml-sitemap.html?op=validate-xml-sitemap&go=1&sitemapurl=https%3A%2F%2Fdocs.mdanalysis.org%2F1.0.0%2Fsitemap.xml&submit=Validate+Sitemap)
- [x] https://userguide.mdanalysis.org/1.0.0/sitemap.xml – [2 errors](https://www.websiteplanet.com/webtools/sitemap-validator/?page=https://userguide.mdanalysis.org/1.0.0/sitemap.xml)
- [x] https://www.mdanalysis.org/pmda/sitemap.xml – [2 errors](https://www.websiteplanet.com/webtools/sitemap-validator/?page=https://www.mdanalysis.org/pmda/sitemap.xml)
- [x] https://www.mdanalysis.org/GridDataFormats/sitemap.xml — [2 errors](https://www.websiteplanet.com/webtools/sitemap-validator/?page=https://www.mdanalysis.org/GridDataFormats/sitemap.xml)
- [x] https://www.mdanalysis.org/MDAnalysisData/sitemap.xml – [2 errors](https://www.websiteplanet.com/webtools/sitemap-validator/?page=https://www.mdanalysis.org/MDAnalysisData/sitemap.xml)
- [x] https://www.mdanalysis.org/RotamerConvolveMD/sitemap.xml — [2 errors](https://www.websiteplanet.com/webtools/sitemap-validator/?page=https://www.mdanalysis.org/RotamerConvolveMD/sitemap.xml)
- [x] https://www.mdanalysis.org/sitemap.xml (note: this had _not_ been included in the sitemapindex.xml..., see https://github.com/algolia/docsearch-configs/issues/2103#issuecomment-659962180) — [2 errors](https://www.websiteplanet.com/webtools/sitemap-validator/?page=https://www.mdanalysis.org/sitemap.xml), [valid](https://www.xml-sitemaps.com/validate-xml-sitemap.html?op=validate-xml-sitemap&go=1&sitemapurl=https%3A%2F%2Fwww.mdanalysis.org%2Fsitemap.xml+&submit=Validate+Sitemap)

**Comment by orbeckst** [comment]
According to the validator, all our [sphinx-sitemap](https://github.com/jdillard/sphinx-sitemap) generated sitemaps have the error

> Line pos
> 2               XML declaration allowed only at the start of the document

**Comment by lilyminium** [comment]
Is that an actual error? All the sitemaps have `<?xml version='1.0' encoding='utf-8'?>` in line 1. I presume the culprit is `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`, but the internet doesn't think XML namespaces must be declared at the start of the document; is it a false positive or an algolia thing?

**Comment by orbeckst** [comment]
I don't think that algolia is particularly troubled, just this particular validator flags an error. Other validators such as https://www.xml-sitemaps.com/validate-xml-sitemap.html do not detect any issues with the sitemaps.

**Comment by orbeckst** [comment]
The real problem was that I hadn't included the main site sitemap in the sitemapindex – thank you for spotting it https://github.com/algolia/docsearch-configs/issues/2103#issuecomment-659962180. This sitemap.xml is generated on the fly (or rather, on deployment on GitHub's side) so it wasn't obvious that it was there.  When you deploy locally it is built (as a local version) in `_site/sitemap.xml`.

Let's see if algolia now also includes the website. Once that's there we can think about reweighting, e.g., make results from the user guide and the website have more weight.

**Comment by orbeckst** [comment]
Given that https://www.xml-sitemaps.com/validate-xml-sitemap.html validates all our sitemaps and the siteindex and the 2 errors that we find don't really seem to be an error, we will consider our maps valid.
