### ISSUE TITLE
remove links to outdated tutorials

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#147]
The [learning MDAnalysis](https://www.mdanalysis.org/pages/learning_MDAnalysis/) page is one of the most visited ones according to [mdanalysis.goatcounter.com](https://mdanalysis.goatcounter.com/?hl-period=month&period-start=2020-06-24&period-end=2020-07-24&filter=&showrefs=%2Fpages%2Flearning_MDAnalysis) so we should pay attention to what's on there.

In particular, it still suggests users should look at https://www.mdanalysis.org/MDAnalysisTutorial/ . I think that this can be removed and instead users should be directly directed to read the [User Guide](https://userguide.mdanalysis.org). It would be sufficient to just have a sentence somewhere that links to the [Other Tutorials](https://github.com/MDAnalysis/mdanalysis/wiki/Tutorials) wiki page for any additional readings.

**Comment by orbeckst** [comment]
@lilyminium is there anything in the old MDAnalysisTutorial that is not covered in the Quickstart Guide and that would justify keeping the old tutorial hanging around in a prominent position?

(I don't have any tracking data for the old tutorial because we never tracked the pages with analytics.)

**Comment by lilyminium** [comment]
> is there anything in the old MDAnalysisTutorial that is not covered in the Quickstart Guide and that would justify keeping the old tutorial hanging around in a prominent position?

The most significant difference is that the old tutorial has exercises with worked solutions, while the quickstart guide just lays out information. However, I can fold that in quite easily for the most part, or make them much smaller examples ("getting-info-from-atomgroups.ipynb") and link to them.

**Comment by orbeckst** [comment]
Is there a way to use something like https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/exercise/readme.html so that solutions are initially hidden?
