### ISSUE TITLE
redirect old mdanalysis.org/docs to to docs.mdanalysis.org

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#155]
It's confusing to have different versions of docs at https://docs.mdanalysis.org/ and https://mdanalysis.org/docs. (Right now, the former shows 1.0.0 with date Sep 01, 2020 and the latter 1.0.0 from Jun 10, 2020.)

Perhaps the best thing to do would be a redirect (or a page rule) from https://mdanalysis.org/docs to https://docs.mdanalysis.org/1.0.0/.

- [x] redirect (docs -> 1.0.0)
- [x] remove /docs from search indexing/sitemap

**Comment by orbeckst** [comment]
@lilyminium did we consider this issue before?

**Comment by lilyminium** [comment]
Yes, I think we decided a PageRule was best. If we're out of PageRules we could set a permanent redirect as `mdanalysis.org/docs` is its own repo, but the former seems easier.

**Comment by lilyminium** [comment]
> Do you expect a difference in behavior for search engines, i.e., does the permanent redirect instruct them to update their entries while the PageRule doesn't?

No I think they just both do a permanent HTML redirect in the end. 

> If we use the PageRule then we could disable publishing the docs repository at mdanalysis.org/docs, right?

Yeah :-) I did have a look and we do already have 3 PageRules in place. One of them redirects ``docs.mdanalysis.org/*`` pages to ``docs.mdanalysis.org/2.0.0-dev0/*`` pages, but I can replace with redirects the way I've done for the user guide for now. (It should probably go to the 1.0.0 version anyway). I'll do the latter first, tonight, then update the page rules.

**Comment by lilyminium** [comment]
Slightly on hold until Parmed fixes their site and docs can build again.

**Comment by lilyminium** [comment]
www.mdanalysis.org/docs/ should redirect to docs.mdanalysis.org/1.0.0 now. I hardcoded the 1.0.0 into the PageRule (instead of pointing to ``docs.mdanalysis.org/$1``) to avoid chaining redirects, which I think can dilute SEO link value, make the browser think we're spammers, and make things a bit slower for users on slow connections. This is noted [on the wiki](https://github.com/MDAnalysis/MDAnalysis.github.io/wiki/DNS#existing-subdomain-forwards) but should maybe go into a "release to-do"s page as it should get updated for each release.

**Comment by orbeckst** [comment]
Thanks. Adding it to the “TODO for releases” would be good. We could make a kind of themplate for the “make release” issue and add it to the list of things to check off.

**Comment by orbeckst** [comment]
I updated the [DNS wiki page](https://github.com/MDAnalysis/MDAnalysis.github.io/wiki/DNS) a bit. Could you please check for errors when you have a chance, please @lilyminium ? I removed some of the historical view and present the current state.

I also added notes to https://github.com/MDAnalysis/mdanalysis/wiki/PreparingReleases — @lilyminium and @richardjgowers please have a look. In particular, now master branch docs also build automatically so some sections on manual docs building and uploead were removed. But the Clouflare Pagerule needs manual updating.

Can we remove the https://github.com/MDAnalysis/docs repo now (or at least retire it)?

Once you're ok with the Wiki documentation

**Comment by orbeckst** [comment]
The search config is already excluding `"https://www.mdanalysis.org/docs",` as a `stop_url`.

**Comment by lilyminium** [comment]
With the new "stable" endpoint, we shouldn't need to manually edit redirects from www.mdanalysis.org/docs anymore (I've updated the PageRule and the DNS wiki page to reflect that). The stable sitemap.xml still refers to the 1.0.0 URLs, though, which I think is non-kosher for sitemaps. If I update to stable/ URLs we shouldn't need to manually update the website sitemapindex.xml either I shouldn't think.

**Comment by orbeckst** [comment]
> The stable sitemap.xml still refers to the 1.0.0 URLs, though, which I think is non-kosher for sitemaps.

Yes, technically that's not allowed.

For the search we should actually exclude "stable", "latest", "dev" because they already exist with version numbers and we'd like to avoid showing duplicates. Or should we do the opposite and only include "stable" in the search and exclude everything else from the search? Or just "stable" and "dev" (which will mostly produce duplicates but allow developers to occasionally find the thing that's not in stable yet)?

**Comment by orbeckst** [comment]
> Edit: and yes I think the docs repo is now redundant!

Should we delete the repo? Is there a reason why we might want to keep it?

**Comment by lilyminium** [comment]
I think either stable/ and dev/, or just stable/ if you want to avoid duplicates -- that way it'll update automatically and it is clearer to the user that what they're looking at (whereas pointing to 1.0.0 can raise questions like "is this the latest version"). They can also search within docs versions if they're looking for a particular results.

> Should we delete the repo? Is there a reason why we might want to keep it?

I can't think of any? @MDAnalysis/coredevs? The URL already points to docs.mdanalysis.org.

**Comment by orbeckst** [comment]
Then let's point the algolia search to *stable/ only* and block anything else. In this way our users only see released features on first search from the website. Search inside the docs works as before, of course.

**Comment by orbeckst** [comment]
I deleted MDAnalysis/docs.
