### ISSUE TITLE
use {{site.baseurl}} everywhere

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#16]
It's not always straightforward to make the Hyde theme run as a GitHub pages and also locally with the jekyll server for debugging. I found that _unless one serves from the root `/`_ one has to use `{{site.baseurl}}` everywhere. Admittedly, we have `site.baseurl == /` so everything works but a cleaner solution is to _always_ prefix links with `{{site.baseurl}}`.

I.e., whenever you write a local link like `/blog/pages` you should be writing `{{site.baseurl}}pages`.

Similarly, we should change the short variables in `_config.yml` to be relative 

``` yml
﻿﻿images:  images/
blog:       blog/
```

and always prefix with `{{site.baseurl}}` in the Jekyll templates:

``` markdown
bla bla see the [latest blog post]({{site.baseurl}}{{site.blog}}pages/) bla
```

(One cannot use variable expansion inside the `_config.yml` file e.g. `blog: {{site.baseurl}}blog/`, apparently Jekyll only does a single pass and does not expand variables within variables.)

In this way we are always guaranteed that local and remote versions of the site are served consistently.

**Comment by mnmelo** [comment]
From what I could figure out (with minimal checking) `paginate_path` is always appended to `site.baseurl` so we don't need to worry about that one. Only thing is that if we change the `blog` dir we have to also change it in `paginate_path` (unavoidable duplication given the single-pass issue @orbeckst mentioned?)

**Comment by orbeckst** [comment]
Note: site just broke because GitHub Jekyll now appears to be removing the trailing slash from `site.baseurl`. Need to rewrite everything to look like `{{ site.baseurl }}/blah` (i.e., include the slash).

**Comment by orbeckst** [comment]
According to https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/ we do NOT need `site.baseurl` when we are serving from the top base url, i.e., `/`. 

(For #73 I needed to set it to empty and I will check the rest of the site that this is not breaking anything.)

**Comment by orbeckst** [comment]
Closing because we keep `site.baseurl` empty anyway.
