### ISSUE TITLE
Regarding spelling mistake in "ABOUT" file in the home page under WIKI.

### ISSUE THREAD

**Issue by Kartik-Khandelwal** [MDAnalysis/MDAnalysis.github.io#161]
![image](https://user-images.githubusercontent.com/69040018/99785497-12b0af80-2ad2-11eb-95a9-e944551f5210.png)

There is a mistake **"scientific"** is misspelled as **"scientifc"**.

**Comment by Kartik-Khandelwal** [comment]
May i solve this issue.

**Comment by IAlibay** [comment]
@Kartik-Khandelwal by all means, please do open a PR.

**Comment by Kartik-Khandelwal** [comment]
@IAlibay your welcome, I am focusing on GSoC 21.

Please guide me how do i contribute more on mdanalysis.

**Comment by IAlibay** [comment]
> Please guide me how do i contribute more on mdanalysis.

@Kartik-Khandelwal this is probably best handled on the mailing list. My suggestion here would be to look at any issues labeled `gsoc` and/or `help wanted` and see what can be worked on.

> I am focusing on GSoC 21.

I should point out that the MDAnalysis team hasn't made a decision on whether or not we will take on students for GSOC this year. Early interest is appreciated and will increase chances of us taking part, but it is worth keeping in mind that it is not guaranteed.
