### ISSUE TITLE
add marrink-lab/MDVoxelSegmentation to used-by

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#178]
After Bart's excellent talk we should really list [MDVoxelSegmentation](https://github.com/marrink-lab/MDVoxelSegmentation) on our used-by page.

https://github.com/marrink-lab/MDVoxelSegmentation/issues/111

(Also, maybe we can get @BartBruininks to write a blog post for us with included videos?)

**Comment by BartBruininks** [comment]
Sorry, for my late reply I must have missed this one. I think the link is a cool idea and I wouldnt mind writing a blogpost.

**Comment by orbeckst** [comment]
@BartBruininks you can add the link by editing https://github.com/MDAnalysis/MDAnalysis.github.io/blob/master/pages/used-by.md in your browser--- it will create a PR for you.

**Comment by orbeckst** [comment]
@BartBruininks  I am inviting you to write a blog post about your work — I am sure that the rest of the @MDAnalysis/coredevs will also love to see a blog post on MDVoxelSegmentation. 

Create a PR and follow the examples in https://github.com/MDAnalysis/MDAnalysis.github.io/tree/master/_posts . We'll review the post (so give it a date a week in the future so that we have enough time for review). Images, links, etc are welcome, you can also embed a YouTube video if you like. We'll be happy to help.
