### ISSUE TITLE
announcement post

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#188]
embargoed until 9 am Pacific Time on Tuesday, August 31, 2021. 

- [ ] blog
- [ ] tweet

**Comment by richardjgowers** [comment]
Ooooh mystery post, what could it be?

**Comment by IAlibay** [comment]
Obviously the announcement of MDAWKnalysis, the AWK layer for MDA.

**Comment by orbeckst** [comment]
Close, although we opted for a slightly [more modern language](https://www.perl.org/).
