### ISSUE TITLE
use subdomains in docs

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#2]
I set up domain redirects (domain forwarding) for a number of subdomains. We should use those subdomains instead of deeply-linked URLs because that will give us more flexibility in the future.

For instance, [www.mdanalysis.org](http://www.mdanalysis.org) redirects to http://mdanalysis.github.io and [wiki.mdanalysis.org](http://wiki.mdanalysis.org) sends you to https://github.com/MDAnalysis/mdanalysis/wiki. That means one can link to a wiki page like https://github.com/MDAnalysis/mdanalysis/wiki/Install as http://wiki.mdanalysis.org/Install

For more details and the full list of subdomains, see the wiki page on **[DNS: Subdomains](https://github.com/MDAnalysis/MDAnalysis.github.io/wiki/DNS#subdomains)**.

**Comment by richardjgowers** [comment]
Would it be possible to add a subdomain for the user discussion group? (help.mdanalysis? mailinglist.mdanalysis? users.mdanalysis? I'mbadatnames.mdanalysis?)

**Comment by orbeckst** [comment]
Good idea. I set up help and users to point to the user list. 

--
Oliver Beckstein
email: orbeckst@gmail.com
skype: orbeckst


Am Apr 15, 2015 um 1:58 schrieb Richard Gowers <notifications@github.com>:

**Comment by orbeckst** [comment]
Just added subdomains *help*, *users* and *discussion* — they all point to the [user discussion mailing list](http://groups.google.com/group/mdnalysis-discussion).
