### ISSUE TITLE
add conda installation instructions

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#20]
Once PR MDAnalysis/mdanalysis#751 is merged, which makes MDAnalysis available through `conda` MDAnalysis/mdanalysis#608 , we need to document this
- [x] add to Quickstart Installation
- [x] blog post

Also update the tutorial (MDAnalysis/MDAnalysisTutorial#7).

**Comment by orbeckst** [comment]
Should we say in the post that the conda builds are only serial and that for OpenMP builds you should also build locally?

**Comment by kain88-de** [comment]
I thought it sounded so negative when we say that in the end of the post after mentioning osx. I mentioned it on the quick install quide though.

The thing is how many people are actually using the openmp backend? I don't want to scare people of the conda build for something they don't even use.

**Comment by orbeckst** [comment]
Ok, if it's in quick install then it should be fine. Just should be somewhere.
