### ISSUE TITLE
add distopia to search

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#200]
Include the [distopia docs](https://www.mdanalysis.org/distopia) into the site search

- [x] add sitemap https://www.mdanalysis.org/distopia/sitemap.xml to master sitemap
- [ ] check algolia search configuration

**Comment by orbeckst** [comment]
cc @hmacdope just so that you know that this also needs to be done — you can do a PR to add the sitemap to https://github.com/MDAnalysis/MDAnalysis.github.io/blob/master/sitemapindex.xml if you like and I can check if the search needs anything

**Comment by hmacdope** [comment]
See #201

**Comment by orbeckst** [comment]
Now that PR #201 is merged, we need to give algolia some time to notice and index the site.

If it's not showing up in our search in 24h then something else needs fixing.

**Comment by orbeckst** [comment]
I searched for "distopia" and "CalcBondsOrtho" and now hits, so I am re-opening. (Probably similar issues as #199 )

**Comment by orbeckst** [comment]
I raised #202 for the missing search results.
