### ISSUE TITLE
add CZI to Partners in About

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#206]
With the CZI grant start date coming up, we need to add CZI with its logo to the **Partners** section in the [About](https://www.mdanalysis.org/about/#partners) page.

**Comment by IAlibay** [comment]
We'll need to reach out to CZI and get their official logo / branding for this.

**Comment by orbeckst** [comment]
I am asking on slack in #opensci-eoss-grantees.

**Comment by orbeckst** [comment]
Logo to be used (from Carly Strasser @ CZI)
![CZI_Logo](https://user-images.githubusercontent.com/237980/142516011-2abf18f1-e261-4610-a2ca-37adde7836cb.jpg)
