### ISSUE TITLE
Edis Jakupovic's NSF REU blog post

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#208]
@edisj you're invited to write a blog post on the MDAnalysis blog https://www.mdanalysis.org/blog/ about your NSF REU work on implementing H5MD capabilities in MDAnalysis.

There are no real limitations. You may want to have a look at recent GSoC posts to get an idea what students write.

Please submit a PR with the blog post in a file under [_posts](https://github.com/MDAnalysis/MDAnalysis.github.io/tree/master/_posts) with a name like YYYY-MM-DD-NSF-REU-edis.md (in markdown format). Set the date to 1 week into the future of your current date to provide some time for review.

Thank you!

**Comment by edisj** [comment]
@orbeckst  Yes it is, I will make some time for it in the near future

**Comment by orbeckst** [comment]
@edisj is this something you want to get around to? Otherwise I'll close.

**Comment by edisj** [comment]
> @edisj is this something you want to get around to? Otherwise I'll close.

@orbeckst sorry! I'll set a deadline for this weekend and have the rough draft posted

**Comment by edisj** [comment]
I didn't have have much time as I thought over the weekend. I have a rough draft in the works and should have a completed version pushed during this week

**Comment by orbeckst** [comment]
I am going to close this one for now. If you want to write the post let me know and we re-open.
