### ISSUE TITLE
relicensing blog post

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#248]
Describe plan for relicensing.

**Comment by IAlibay** [comment]
Proposed tweet:

```
Tweet 1/2 

We are looking to change the license for the <at-MDAnalysis> Python library from GPLv2+ to LGPLv3+. This will allow folks to more freely choose which license to use when developing codes which use MDAnalysis. Our full rationale for this is outlined in the following blog post: <link> 

Tweet 2/2

We want to use the next month to engage with the community, listening to any comments or questions you may have about this. Please join the conversation on our mailing list <link>, discord <link>, or by emailing us directly licensing-at-mdanalysis.org
````

**Comment by IAlibay** [comment]
Proposed email (to both the dev and community mailing lists):

```
Dear MDAnalysis community members (or developers based on list):

We are proposing changing the license for the MDAnalysis core library from the current GPLv2+ to LGPLv3+. The reasons for this are varied, but can mostly be summed up to a need for better licensing freedom for downstream users of the MDAnalysis library. Whilst GPLv2+ has been an effective license for MDAnalysis over the years, it has (at least by our interpretation) the key limitation of enforcing its copyleft on codes that import and/or otherwise use the library components. To this end, we have propose the LGPLv3+ as a replacement license for MDAnalysis which would avoid this issue altogether.

We invite you to read the following blog post where we lay out the our complete rationale for this license change: <link to blog post>

From today until the 5th of December 2022, we would like have a consultation period on this proposed license change. During this period we would like to encourage members of the community to share their thoughts / questions on the topic either here, on our discord, or privately to the core developer team by email to liscensing@mdanalysis.org.

We are fully invested in ensuring that our actions reflect the needs of our community, and it is important that we hear any views you may have on the subject before we start this process.

Best regards,

The MDAnalysis Core Developer Team

**Comment by orbeckst** [comment]
> During this period we would like to encourage members of the community to share their thoughts / questions on the topic either here, on our discord, or privately to the core developer team by email to [liscensing@mdanalysis.org](mailto:liscensing@mdanalysis.org).

During this period we would like to encourage members of the community to share their thoughts / questions on the topic either here on the mailinglist, on our discord (https://www.mdanalysis.org/#participating), or privately to the core developer team by email to [licensing@mdanalysis.org](mailto:licensing@mdanalysis.org).

I assume that the email is really `licensing@mdanalysis.org`.

**Comment by IAlibay** [comment]
O no we both did the same thing at the same time @orbeckst 🙈

**Comment by lilyminium** [comment]
Suggestion for tweets:

Tweets:

```
Hello #compchem! We want to change the license of @MDAnalysis from GPLv2+ to LGPLv3+. This means that you'll have more freedom in choosing your own license when you develop code that uses MDAnalysis. We want to get your thoughts! Details below :downwards-pointing-finger: #hashtagsgalore
```

```
Over the next month (until Dec 5th) we will have an open consultation period to listen to your comments, questions, and any other feedback you have. Please join the conversation on our mailing list <link>, discord <link>, or by emailing us directly licensing-at-mdanalysis.org . Summaries of discussion and FAQs will be up at <wiki link>. Our rationale and relicensing process is here: < blog link >
```

--- Summary tweets follow after this ---

```
@MDAnalysis was initially released under GPLv2+ so that anyone can freely use, contribute, and build on it. But GPLv2+ requires code importing or using MDAnalysis to also adopt a compatible GPL license. This heavily restricts the licenses that downstream developers can use, creating barriers to adoption.
```

```
We think the LGPLv3+ is a better choice for @MDAnalysis now. Like the GPLv2+, code that copies or extends MDAnalysis must also have a compatible open-source license. However, code that only *uses* MDAnalysis is free to have any license it likes -- including commercial, closed-source licenses.
``` (part after dash might be a bad idea)

```
So far, 160+ people have contributed to the MDAnalysis library. We are a community-driven project and ultimately want our actions to reflect the needs of our community. Therefore we'll have an open consultation period until December 5th 2022 for questions, comments, and other feedback.
```
```
After this period, we will start contacting every code contributor to ask them if they are willing to change their contribution's license to LGPLv3+. We will make our best effort to contact as many contributors as possible. During this time we will continue engaging with our community on questions and concerns.
```

```
We don't know how long relicensing will take. We expect contacting all our contributors to be a long and slow process. However, we believe this effort is worthwhile for the huge benefit it will bring to the MDAnalysis community. We will keep updating regularly on our progress.
```

Last one could be more inspiring. I haven't checked character counts.

**Comment by IAlibay** [comment]
@lilyminium the first two are fine, but I'd like to avoid the rest if that's ok? The blog post is there and is ratified with all the warnings. If folks want more info they should just read the blog post.

**Comment by lilyminium** [comment]
I'd rather throw in a tweet with the legal warnings? It's easier to ask people to just scroll down on Twitter than to click and read, IMO.

**Comment by orbeckst** [comment]
My opinion: For important things such as relicensing there should be ideally only one source of truth. I very much like the tone of your initial tweets, @lilyminium , so I would go with those or a version of them. What I'd want to avoid is having to check that tweets and blog post really say the same thing. Personally I wouldn't want _any_ confusion whatsover over what we say. If in doubt, I consider our own blog the only source that really matters.
