### ISSUE TITLE
GSoC completion blog post

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#249]
Once GSoC is completed for our students, summarize their projects and link to their final blog posts.

**Comment by orbeckst** [comment]
For reference: final blog posts

* @BFedder : https://bfedder.github.io/jekyll/update/2022/09/26/the-end.html
* @aya9aladdin : https://sites.google.com/pharma.asu.edu.eg/aya-gsoc/final-week-of-gsoc

**Comment by IAlibay** [comment]
Blocker: We need to get the userguide to work ahead of this, it won't look great for us if we can't even point to the right place.

**Comment by IAlibay** [comment]
> Blocker: We need to get the userguide to work ahead of this, it won't look great for us if we can't even point to the right place.

Pseudo fixed, see: https://github.com/MDAnalysis/mdanalysis/pull/3885
I think the only thing left after that was that @BFedder wanted to add some matplotlib plot directives, which shouldn't take much time.

**Comment by BFedder** [comment]
Ping! The matplotlib plot directive is now working, so my PR (https://github.com/MDAnalysis/UserGuide/pull/230) is ready for review.

**Comment by hmacdope** [comment]
Skeleton post is now up in #252 

@MDAnalysis/gsoc-mentors Do we want to follow the same format as last year where each student does and individual wrap up post or would we like to just link to their final summaries on their blog and some userguide stuff?

@jbarnoud @micaela-matta @richardjgowers @lilyminium (outreachy people, apologies if I have missed anyone) I have left the Outreachy section blank so you can fill in with what you want.

**Comment by orbeckst** [comment]
I liked the format where each student got an opportunity to write their own blog post.

**Comment by hmacdope** [comment]
Unless people say otherwise  we will go with a post each. I'll raise new issue for each one.

**Comment by BFedder** [comment]
Linking last year's completion posts here, mostly for my own convenience but also in case they might be useful for @aya9aladdin and @umak1106 

https://www.mdanalysis.org/blog/page5/#gsoc-report-solvation-analysis

https://www.mdanalysis.org/blog/page5/#gsoc-report-curvature-for-mda-universes
