### ISSUE TITLE
MDAnalysis stickers

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#25]
@kain88-de had the  idea to make stickers so that we can hand them out at conferences and workshops (and of course, to stick them on our own laptops or bikes). I ordered 300 stickers 1.96" x 2" from http://www.stickermule.com :

![mda_proofs](https://cloud.githubusercontent.com/assets/237980/14885052/5c77c9d8-0d49-11e6-97fe-9f1f0cdbe98f.png)

@MDAnalysis/coredevs – who wants some to spread the goodness? Let me know through the issue tracker and then we can figure out a sensible distribution system.

**Comment by kain88-de** [comment]
I would like some.

**Comment by richardjgowers** [comment]
Yep me too

**Comment by jbarnoud** [comment]
Me too.

**Comment by mnmelo** [comment]
Me too (and I can share the same shipment as Jonathan's)

**Comment by hainm** [comment]
I told @dotsdl  at Biophysics conference that MDA has very pretty logo.

**Comment by orbeckst** [comment]
Thanks, I'll tell [my brother](https://twitter.com/chrisbeckstein), who designed the logo :-)

**Comment by orbeckst** [comment]
Btw, stickers to arrive May 6. Please email me your postal addresses. So far I have "Wants" from

* @kain88-de (Germany)
* @richardjgowers (Scotland)
* @jbarnoud and @mnmelo (combined shipment to Groningen)
* @orbeckst and @dotsdl (AZ)

Anyone else: let me know soon so that we can split the numbers accordingly. The current plan is to send between 30 and 40 to each developer on the list above and keep the remainder as a stash here so that we can send out more when needed (e.g. for GSoC participants).

I'll also send a few to @nmichaud and the [designer of the logo](https://twitter.com/chrisbeckstein).

**Comment by orbeckst** [comment]
Stickers are on their way. Please let me know once you receive them, just so that I get a sense for how long shipping typically takes. (My experience with US-Europe mail is that this can take *weeks*.)

Core developers who wanted stickers got 35, with the idea that they can distribute them further. Our GSoC students got stickers, too (and @fiona-naughton can distribute some to the other Oxford devs like @tylerjereddy or @jandom if they want any). Some individuals with ties to MDAnalysis also got a few stickers to play with. I have 10 stickers left as a reserve.

| name            | GitHub            | country     | stickers |
|-----------------|-------------------|-------------|----------|
| Max             | @kain88-de        | Germany     | 35       |
| Richard         | @richardjgowers   | UK          | 35       |
| Jonathan        | @jbarnoud         | Netherlands | 35       |
| Manel           | @mnmelo           | Netherlands | 35       |
| David           | @dotsdl           | AZ, US      | 35       |
| Oliver          | @orbeckst         | AZ, US      | 35       |
| John     | @jdetle           | US          | 15       |
| Fiona   | @fiona-naughton , @tylerjereddy , @jandom , SBCB, ...  | UK          | 40       |
| Naveen          | @nmichaud         | US          | 10       |
| Chris  | [@chrisbeckstein](https://twitter.com/chrisbeckstein)   | Germany     | 5        |
| Phil      | @philipwfowler    | UK          | 10       |
|                 | TOTAL DISTRIBUTED |             | 290      |
| reserve           | stash             | AZ, US      | 10       |

Share the goodness, I will distribute some at SciPy and wherever else I find an opportunity. (Anyone who sees me somewhere and either tells me that they are using MDAnalysis or just want a sticker will certainly get one :-)).

(Let me know if you run out of stickers; if there's high demand we can do another print run.)

**Comment by orbeckst** [comment]
We can also *sell* the sticker (all proceeds of the 33% mark-up that I slapped onto the base price go to MDAnalysis....):

<div style="position: relative; max-width: 320px;"><div style="padding: 30px 0px 0px 0px;display: table;background-color: #e9e9e9;border-top-right-radius: 4px;border-top-left-radius: 4px;text-align: center;position: relative;min-height: 327px;width: 100%;"><div style="display: table-cell;vertical-align: middle;"><img src="https://www.stickermule.com/en/marketplace/embed_img/12503" style="max-width:100%;"></div></div><div style="padding: 0px 0px 30px 0px;border-bottom-right-radius: 4px;border-bottom-left-radius: 4px;display:table; background-color: #e9e9e9; width:100%;"><div style="text-align: center; display: table-cell;"><a href="https://www.stickermule.com/en/marketplace/12503-mdanalysis" style="display: inline-block;font-size: 1.2rem;padding: 17px 25px;background-color: #5ba4e6;border-radius: 6px;overflow: hidden;text-align: center;vertical-align: middle;cursor: pointer;border: none;color: #FFF;font-weight: bold;font-family: 'Helvetica Neue',Helvetica, Arial, sans-serif;text-shadow: 0px -1px 0px rgba(0, 0, 0, 0.25);letter-spacing: 0px;line-height: 1.2;-webkit-font-smoothing: antialiased;-webkit-box-shadow: inset 0px -2px 0px rgba(0, 0, 0, 0.15);-ms-box-shadow: inset 0px -2px 0px rgba(0, 0, 0, 0.15);-moz-box-shadow: inset 0px -2px 0px rgba(0, 0, 0, 0.15);-o-box-shadow: inset 0px -2px 0px rgba(0, 0, 0, 0.15);box-shadow: inset 0px -2px 0px rgba(0, 0, 0, 0.15);text-decoration: none;">Buy this sticker</a></div></div></div><div style='font-family: "Helvetica Neue", Helvetica, Arial, sans-serif'>Designed by&nbsp;<a href="https://www.stickermule.com/en/user/1070736800">Oliver Beckstein</a> on&nbsp;<a href="https://www.stickermule.com">stickermule.com</a></div>


P.S.: The price for a *single* sticker is pretty outrageous at $3.71; when buying 300 in bulk the actual cost per sticker is about $0.31.

**Comment by dotsdl** [comment]
Thanks @orbeckst! This is great! The SciPy [talk list](http://scipy2016.scipy.org/ehome/146062/332963/) features several talks/posters that look like molecular/structural biology folks, so we might have a decent audience for these there.

**Comment by richardjgowers** [comment]
My stickers arrived! Very cool too.

**Comment by mnmelo** [comment]
Aww, I left Groningen today for a tour of meetings ; @jbarnoud will be away till the end of the month. We won't be able to pinpoint the arrival of the stickers...

**Comment by fiona-naughton** [comment]
Mine arrived (at least by) yesterday! I've been distributing them to fellow SBCBers today :)

**Comment by kain88-de** [comment]
they also arrived in Germany yesterday.
