### ISSUE TITLE
GSOC summary post Aya

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/MDAnalysis.github.io#254]
We would like to make a collective  summary post for GSOC and outreachy (see #249 and #252). To do this we need a project summary post from each student. @aya9aladdin  this is the issue that will track your post. :) 

Have a look at last years summary posts if you need inspiration.

**Comment by aya9aladdin** [comment]
I added my blog post here (https://github.com/MDAnalysis/MDAnalysis.github.io/pull/260)

**Comment by orbeckst** [comment]
PR #260 was merged.
