### ISSUE TITLE
Outreachy summary post Uma

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/MDAnalysis.github.io#255]
We would like to make a collective  summary post for GSOC and outreachy (see #249 and #252). To do this we need a project summary post from each student. @umak1106 this is the issue that will track your post. :) 

Have a look at last years summary posts if you need inspiration.

**Comment by umak1106** [comment]
> We would like to make a collective  summary post for GSOC and outreachy (see #249 and #252). To do this we need a project summary post from each student. @umak1106 this is the issue that will track your post. :) 
> 
> Have a look at last years summary posts if you need inspiration.

Ok . I'll get the summary post done .

**Comment by hmacdope** [comment]
@umak1106 any progress on summary post?
