### ISSUE TITLE
MDAnalysis 2.4.x release blog

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/MDAnalysis.github.io#266]
## TODO

- [ ] write blog
- [ ] tweet it out

**Comment by IAlibay** [comment]
I've started working on this but was mostly distracted by trying to put together some thoughts for licensing, it's going to have to wait until the UK tomorrow I'm afraid :(

**Comment by orbeckst** [comment]
Should we change the title to "2.5" ? ;-)

**Comment by IAlibay** [comment]
Probably will just do a 2.4.0-2.5.0 - releases are a massive time hog from getting all the milestone PRs done to fixing conda-forge (especially given that we now have to fix the userguide at the same time), and usually at extremely inconvenient times.

If it's acceptable to just take the (in my opinion reasonably detailed) release notes I write (https://github.com/MDAnalysis/mdanalysis/releases/tag/package-2.4.0), stick them in a markdown file and call it a day then we can just do that quickly I guess?

**Comment by RMeli** [comment]
+1 for release notes as blog post for minor releases.

**Comment by orbeckst** [comment]
Totally happy with your proposed approach!Am 4/21/23 um 11:19 schrieb Irfan Alibay ***@***.***>:﻿
Probably will just do a 2.4.0-2.5.0 - releases are a massive time hog from getting all the milestone PRs done to fixing conda-forge (especially given that we now have to fix the userguide at the same time), and usually at extremely inconvenient times.
If it's acceptable to just take the (in my opinion reasonably detailed) release notes I write (https://github.com/MDAnalysis/mdanalysis/releases/tag/package-2.4.0), stick them in a markdown file and call it a day then we can just do that quickly I guess?

**Comment by orbeckst** [comment]
That's closed with PR #293 (and https://twitter.com/mdanalysis/status/1665778747222659072 )
