### ISSUE TITLE
Update recommended citation?

### ISSUE THREAD

**Issue by mnmelo** [MDAnalysis/MDAnalysis.github.io#27]
(Apologies if this has already been debated, but I couldn't find it.)
With the SciPy proceedings paper [online and citable](http://conference.scipy.org/proceedings/scipy2016/oliver_beckstein.html) should we update the recommended citation in www.mdanalysis.org?

If so, will we:

1. show both the old and new citations in the website but only request that the new one is cited;

1. show both citations but only request that the old one is cited;

1. show and request both citations;

 and for completion...
1. show and request only the new citation;

1. show and request only the old citation.

I vote for 1.

**Comment by hainm** [comment]
"3" is more appropriate.

**Comment by orbeckst** [comment]
Generally, both (i.e., **3**) because I see the SciPy paper as an update to the J Comp Chem paper. Once we have a full "MDAnalysis 1.0 paper" we will drop the J Comp Chem paper.
