### ISSUE TITLE
Update CoC with approved changes

### ISSUE THREAD

**Issue by jennaswa** [MDAnalysis/MDAnalysis.github.io#314]
The current CoC committee (@jennaswa, @micaela-matta, and @richardjgowers) met on September 1, 2023 to discuss proposed updates to the MDAnalysis CoC and CoC procedures. MDAnalysis/mdanalysis#4289 reflects the proposed changes agreed upon by the committee and requires approval from all core developers.

Once MDAnalysis/mdanalysis#4289 is approved, a PR should be opened to make the same changes on the website.

**Comment by orbeckst** [comment]
@jennaswa can I please leave you in charge to see that the CoC update gets done? Thanks.

**Comment by jennaswa** [comment]
Was previously fixed with [MDAnalysis/MDanalysis.github.io#326](https://github.com/MDAnalysis/MDAnalysis.github.io/pull/326) - sorry to have forgotten to close this issue.
