### ISSUE TITLE
blog post for new topology system

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#32]
We should have a light-weight preview of the new topology system (MDAnalysis/mdanalysis#363), similar to @richardjgowers 's post on MMTF #31. This can easily come before the official 0.16.0 release: it acts as a teaser and we are also slowly introducing some of the *many* new things in 0.16.0 – better do it in pieces. Also having a single post on the topology system makes it easier to link to it.

This can be written in parallel with the actual docs MDAnalysis/mdanalysis#1078, including links into the new docs. (If you use links of the form `http://devdocs.mdanalysis.org/document_pages/...` then we can later easily change it to release docs `http://docs.mdanalysis.org/document_pages/...` ).

UPDATE:

Blog post should contain (gathered from the comments)
- [x] high level description
- [x] motivation/philosophy
- [x] simple examples
- [ ] changes: how to update code and gotchas
- [x] benchmarks (can link to notebook but should be immediately obvious from the post what the performance is), e.g., like the tables in the MDA SciPy paper
- [ ] optional (but nice): history/comments on merge/picture of the original design on the blackboard, ...

This does not have to be exhaustive but we should hit all of the major points. After all, it is the biggest change inside MDAnalysis since its inception.

**Comment by dotsdl** [comment]
Happy to draft this. It's a good opportunity for me to check in with all the work that was done on the new system while I was absent, while at the same time I'm in a good place to write about the core ideas behind it.

**Comment by tylerjereddy** [comment]
If improved performance was a major motivation, it might be nice to see numbers for how much faster most affected operations are, and over what sizes of systems the improvements hold for.

**Comment by kain88-de** [comment]
You should also explain the new warnings. For example about masses reading a PDB

**Comment by dotsdl** [comment]
@tylerjereddy I can rerun my [performance benchmarks](https://gist.github.com/dotsdl/0e0fbd409e3e102d0458) on current `develop` and see what all this amounts to now. If anyone has suggestions for additional benchmarks to include, I'm all ears.

**Comment by dotsdl** [comment]
@kain88-de ah yes, this ties in with guessers (mdanalysis/MDAnalysis#598), right?

**Comment by richardjgowers** [comment]
Yeah, there will be more warnings, but more often than not it's just that people are being given more information.  Definitely good to document the change though.

With benchmarks, the Universe loading is a nice change esp. for large systems.  It's hard to pin down what a "standard" usage of MDA is.  Maybe running it through one of the more complicated analysis modules like RDF/HBondAnalysis/PSA.

**Comment by kain88-de** [comment]
> Definitely good to document the change though.

Yeah warnings are always scary for a new user or and old one when it suddenly pops up after an update.

For the benchmarks. Loading big systems is always good. For example load a ribosome. Pretty much anything big in the PDB that can be found. [MemProdMD](http://sbcb.bioch.ox.ac.uk/memprotmd/beta/) also has some larger membrane proteins with bilayer in atomistic detail.

**Comment by kain88-de** [comment]
@dotsdl any progress on this?

**Comment by dotsdl** [comment]
@kain88-de I think I'll have time this weekend to get this out. I'll get the PR up as soon as I have a draft

**Comment by orbeckst** [comment]
We will also need benchmarks. I am updating the top post with a check list.

**Comment by orbeckst** [comment]
@kain88-de I added the original picture of the draft topology system to the post, sorry, should have included in the PR but forgot. Now live.
