### ISSUE TITLE
create CoC page

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#34]
We need to have our Code of Conduct at http://mdanalysis.org/pages/conduct/.

See MDAnalysis/mdanalysis#1165

**Comment by kain88-de** [comment]
should the page be just a redirect or rendered markdown?

**Comment by orbeckst** [comment]
I would make it rendered markdown because then it looks more integrated but add a link at the bottom to the version-controlled version of the CoC.

> On 7 Feb, 2017, at 06:59, Max Linke <notifications@github.com> wrote:
> 
> should the page be just a redirect or rendered markdown?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by kain88-de** [comment]
Well then we have the CoC two times. In our repositories. The CoC won't change a lot, if ever, so I guess that wouldn't be to bad. To create page I would just need to copy the markdown file from our main repo into the `pages` folder and add some jenkins markup or?

**Comment by richardjgowers** [comment]
Yeah hopefully the CoC won't change so duplicating it isn't a huge issue.
