### ISSUE TITLE
Make a 2.7.0 release blog post

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/MDAnalysis.github.io#347]
Work off this as a template: https://github.com/MDAnalysis/MDAnalysis.github.io/blob/master/_posts/2023-09-02-release-2.6.1.md

- [x] Use the release notes from github
- [x] Change license wording to just say that the package is GPLv3+ but the code contributions made from that one commit are LGPLv2+
- [x] Supported Python versions are 3.9 to 3.12

**Comment by IAlibay** [comment]
@fiona-naughton I'm handing this one to you.

**Comment by orbeckst** [comment]
@fiona-naughton please let me know when you need a review.

I can then do the twitter and bsky, @jennaswa — can you do LinkedIn? 

(I was about to send a quick bsky (bleep??) but thought it would be better if I could include a link to the blog post.)

**Comment by IAlibay** [comment]
This _should_ be done now if folks want to publicize?

**Comment by orbeckst** [comment]
- [x] twitter: https://twitter.com/mdanalysis/status/1743421149911093305
- [x] bsky: https://bsky.app/profile/mdanalysis.bsky.social/post/3kibieyli522f

**Comment by jennaswa** [comment]
- [ ] linkedin: https://www.linkedin.com/posts/mdanalysis_release-270-of-mdanalysis-activity-7149409601870823424-2mdr/

**Comment by IAlibay** [comment]
Alright, looks like we're done here.
