### ISSUE TITLE
update artifact upload action

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#381]
The GH actions gave the following warning

> Deprecation notice: v1, v2, and v3 of the artifact actions
> The following artifacts were uploaded using a version of actions/upload-artifact that is scheduled for deprecation: "github-pages".
> Please update your workflow to use v4 of the artifact actions.
> Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Update any relevant actions.

**Comment by RMeli** [comment]
`actions/upload-pages-artifact@v3` appears to use the correct `actions/upload-artifact@v4`
