### ISSUE TITLE
Advertise MDA/MolSSI workshop

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#382]
Blog post from PR #379 is live at https://www.mdanalysis.org/2024/05/14/ASUworkshop/

advertise at
- [x] discussion forum
- [x] Discord
- [x] Twitter
- [x] Bluesky
- [x] LinkedIn (@jennaswa )
- [x] MolSSI web page (@armcdona)
- [x] ASU PIs (@orbeckst )
- [x] U of A and NAU PIs (@orbeckst )
- [x] Personal networks

**Comment by orbeckst** [comment]
@jennaswa @fiona-naughton if you manage to post something in our forums, twitter, bsky before I get to it please do!! Just tick off the item so that we know it's done. Thank you!

**Comment by orbeckst** [comment]
Discord
```
https://www.mdanalysis.org/2024/05/14/ASUworkshop/

MDAnalysis together with the Molecular Sciences Software Institute (MolSSI) is holding a free, 2-day workshop on June 24th-25th 2024 at Arizona State University in Tempe, Arizona, USA.

This workshop is intended to transform attendees from users to developers and will cover an introduction to MDAnalysis, software best practices, and guide participants through the creation of their own MDAKit.
Registration

    registration deadline May 27, 2024
    register now https://www.mdanalysis.org/2024/05/14/ASUworkshop/#registration



Places are limited to 40 in-person participants; some sessions will be taught in hybrid mode. Register for the online component through the registration link.

A number of bursaries are available for travel and accommodation. Apply as part of registration.
```

**Comment by orbeckst** [comment]
twitter/bsky
```
Register for our joint MDAnalysis/MolSSI workshop at Arizona State University on June 24th-25th 2024. Attendance is free, travel bursaries are available, register for in-person or online attendance at https://www.mdanalysis.org/2024/05/14/ASUworkshop/

Registration deadline is soon, May 27, 2024.

```

**Comment by orbeckst** [comment]
* bsky https://bsky.app/profile/mdanalysis.bsky.social/post/3ksi47jtkd72b
* twitter https://twitter.com/mdanalysis/status/1790493326321582356

**Comment by armcdona** [comment]
For some reason, I can't check off my box in the to-do list, but the [MolSSI advertising page](https://molssi.org/mdanalysis-molssi-workshop-at-arizona-state-university/) is done, and the workshop is the first item under Latest News and Events on the Main molssi.org page.  There a post scheduled to go out on our socials tomorrow and there will be an item in the MolSSI newsletter on Friday.

**Comment by orbeckst** [comment]
Thanks @armcdona ! 

(Not sure what permissions are needed for checkboxes, sorry that I wrongly assumed you could just do it. I checked it off.)

**Comment by jennaswa** [comment]
Thanks, @orbeckst ! Here's a link to the LinkedIn post (the image as the same alt text used above): https://www.linkedin.com/posts/mdanalysis_mdanalysis-is-partnering-with-the-molecular-activity-7196437040387784705-zdNV?utm_source=share&utm_medium=member_desktop.

**Comment by orbeckst** [comment]
Thanks everyone, all the offical advertising is out, please spread through your own networks where it makes sense.
