### ISSUE TITLE
clean up About page

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#50]
The About page duplicates a lot of material on the Home page, in Quick Start, in Citations, ... It needs to be streamlined and filled with content appropriate to About. 

* basic overview
* who we are
  * people (eg core devs)
  * governance
  * CoC
* where we belong and who supports us
  * numfocus
  * GSoC
  * funding agencies (NSF on my part)
* links to the other pages (eg citations, first steps, ...)

**Comment by orbeckst** [comment]
I hope I'll get to this eventually... but I won't complain if anyone else does it.

Feedback and ideas on this page is especially welcome as well as notes on who should be mentioned on this page (e.g., funders).

**Comment by kain88-de** [comment]
I would also vote to remove some of the redundant information from the about page. Like citations, the example or the link to the docs.
