### ISSUE TITLE
new stickers

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#60]
I ordered MDAnalysis stickers from http://www.stickermule.com (funded by NumFOCUS with money left after the developer sprint at ASU this summer):

- stickers 2"x2" (1000)
- fridge magnets 3"x3" (50)

![mda_proofs](https://cloud.githubusercontent.com/assets/237980/14885052/5c77c9d8-0d49-11e6-97fe-9f1f0cdbe98f.png)

@MDAnalysis/coredevs – who wants some to spread the goodness? Let me know through the issue tracker (and if you can estimate how many you want then that will be helpful), send me a mailing address, and I'll send you some.

(This is followup to #25.)

**Comment by kain88-de** [comment]
I'll pick up mine next month when I visit.

**Comment by mnmelo** [comment]
Sorry for the fat fingers closing/reopening this...

I'd be glad to get some stickers/magnets: there's certainly several people here in the institute that'll love to get them. I think 50 stickers/5 magnets should suffice, but please adjust if there's a lot of demand,

Please ship in my name to
```
ITQB NOVA
Av. da República
2780-157 Oeiras
Portugal
```

Thanks!

**Comment by jandom** [comment]
50?! Manuel you have been doing some awesome job converting people! Is it now even biologists using MDAnalysis? :P 

Same here – maybe not 50 stickers but order 20-30, no magnets.

```
Jan Domanski
New Biochemistry Building, Department of Biochemistry
University of Oxford
S Parks Rd
Oxford OX1 3QU
United Kingdom ;-)
```

**Comment by orbeckst** [comment]
@jandom I can send you a few more and you can just leave a pile on Mark's and the Phils' desks....

**Comment by orbeckst** [comment]
Btw, I would reconsider not having fridge magnets, they can be very useful when faced with bending units: https://www.youtube.com/watch?v=MiVozLe181I

**Comment by orbeckst** [comment]
Sorry guys... behind on things, I hope Santa will bring you some stickers.

Anyone else?
