### ISSUE TITLE
serve with SSL encryption

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#61]
mdanalysis.org is served uncencrypted, which will raise browser warnings in the futures. See discussion https://groups.google.com/d/msg/mdnalysis-devel/rhT3mxcIBhc/MNIOQVr6AAAJ

Solution: use cloudflare as DNS provider, follow https://fillmem.com/post/fast-secured-and-free-static-site/ : cloudflare + github-pages + custom domain with https.

See notes at https://github.com/MDAnalysis/MDAnalysis.github.io/wiki/DNS

**Comment by kain88-de** [comment]
awesome thank you. Btw for me everything seems to work with ssl. (FF 55 + https everywhere)

**Comment by orbeckst** [comment]
I transferred DNS from Godaddy to Cloudflare. 
- Got a SSL cert for mdanalysis.org and *.mdanalysis.org. 
- enabled DNSSEC
- transferred the complete DNS zone file from Godaddy to Cloudflare (but kept the Godaddy subdomain forwarding still running – it is tied to A records pointing to Godaddy servers)

The following are working:
- https://www.mdanalysis.org
- https://mdanalysis.org
- https://docs.mdanalysis.org

Any other subdomains (such as http://issues.mdanalysis.org or http://users.mdanalysis.org) only work when accessed unencrypted. (In order to make them also work I would need to pay $5 per month for 5 additional [Cloudflare PageRules](https://blog.cloudflare.com/introducing-pagerules-url-forwarding/) (that I can use for redirects)).

We have one free PageRule left.

**Comment by kain88-de** [comment]
I didn't know the last sub domains existed.

**Comment by orbeckst** [comment]
See https://github.com/MDAnalysis/MDAnalysis.github.io/wiki/DNS#subdomains

**Comment by orbeckst** [comment]
Note that when you go to http://devdocs.mdanalysis.org you are immediately redirected to http://www.mdanalysis.org/mdanalysis/ (by Godaddy) and this in turn is redirected to https://www.mdanalysis.org/mdanalysis/ (by Cloudflare). Thus the actual pages are always served through SSL but it is *not* working to go through ~~https://devdocs.mdanalysis.org~~ directly.

I installed a Cloudflare PageRule for https://docs.mdanalysis.org because this is arguably the most important subdomain and people would expect it to "just work".

**Comment by orbeckst** [comment]
For the record: since May 1, 2018, [Custom domains on GitHub Pages gain support for HTTPS](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/).  If we don't want to use cloudflare anymore, we can use GitHub natively.
