### ISSUE TITLE
Add community page

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/MDAnalysis.github.io#62]
See for example http://pandas.pydata.org/community.html

It's a page that repeats our mailing lists and preferred ways of contact for users and aspiring new developers. I've seen community tabs cropping up on other popular projects as well.

**Comment by orbeckst** [comment]
Good idea, I like it.

**Comment by orbeckst** [comment]
The originally linked page doesn't exist any more. 

Our web page has https://www.mdanalysis.org/#participating and we also have discord ... and we haven't done anything on this issue in 4 years so I am closing.
