### ISSUE TITLE
List of projects using MDAnalysis

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/MDAnalysis.github.io#63]
It would be good to have a list of projects on the website that use MDAnalysis.

from others

- [pytim](https://marcello-sega.github.io/pytim/)
- [pycontact](https://github.com/maxscheurer/pycontact)
- [nglview](https://github.com/arose/nglview)
- [pycazip](https://www.sciencedirect.com/science/article/pii/S2352711016300036)

Ours

-  [RotamerConvolveMD](https://github.com/MDAnalysis/RotamerConvolveMD)

I'm sure I forgot a lot. It would be nice if others could extend that list.

**Comment by orbeckst** [comment]
Perhaps also general distributions that include MDAnalysis (need to do some research if there are any... eg Fedora?). 

More specialized distributions: 
* [NMRbox](https://nmrbox.org/) (see also [dev list thread](https://groups.google.com/d/msg/mdnalysis-devel/g13Dgvn7dEI/UOCLxqcmCgAJ))

**Comment by jbarnoud** [comment]
* [PBxplore](https://github.com/pierrepo/PBxplore) a tool to analyze local structures in proteins using a structural alphabet.
* [cgheliparm](https://github.com/ifaust83/cgheliparm) analyze structures of coarse grained DNA

**Comment by richardjgowers** [comment]
https://github.com/weiHelloWorld/accelerated_sampling_with_autoencoder

**Comment by kain88-de** [comment]
https://github.com/bio-phys/pydiffusion

https://nms.kcl.ac.uk/lorenz.lab/wp/index.php/2019/04/17/mda-pymol/
