### ISSUE TITLE
remove docs from pythonhosted.org

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/MDAnalysis.github.io#64]
https://pythonhosted.org/MDAnalysis/documentation_pages/core/AtomGroup.html

the docs are still available and are the top results under google. It would be great to invalidate them

**Comment by orbeckst** [comment]
I don't know how.

**Comment by orbeckst** [comment]
Well, I found out: on pypi there is a button **Destroy Documentation** with the warning
> If you would like to DESTROY any existing documentation hosted at http://pythonhosted.org/MDAnalysis Use this button, There is no undo. 

Should I do this?

**Comment by kain88-de** [comment]
does it result in a 404 error later?

**Comment by orbeckst** [comment]
I don't know. Probably.

**Comment by kain88-de** [comment]
https://github.com/pypa/pypi-legacy/blob/c6e472593d896af4b2b9f00376cc363f2bb9b3ba/webui.py#L2525

This is the function that is called using the button. They just remove the files. This should result in a 404 error. Afterwards, we only have to tell Google to use the updated links to our Github pages repo.

**Comment by orbeckst** [comment]
Alright – should I push the button?

(I assume that Google will eventually figure it out, or how do you tell Google anything?)

**Comment by kain88-de** [comment]
There should be some docs and forms to tell Google about the changed address. I'm also OK with pushing the button. The docs are outdated anyway.

**Comment by kain88-de** [comment]
@richardjgowers are do you have any last comment why we shouldn't do this as our release manager

**Comment by orbeckst** [comment]
Thanks, totally forgot that we had this issue open. 

--
Oliver Beckstein
email: orbeckst@gmail.com
