### ISSUE TITLE
Blog post for 0.18.0 release

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#69]
Support MDAnalysis/mdanalysis#1800 with post.

**Comment by kain88-de** [comment]
IMHO some short highlight list from the changelog would be.

- universe.copy
- duecredit
- groupby (just mention it again this thing is useful!)
- very good DCD support. I'm sure that our old reader wasn't that accurate.
- gromacs 2018 support.

12 contributors total. 6 first time contributor!

**Comment by richardjgowers** [comment]
@kain88-de yeah I'm writing this right now

**Comment by orbeckst** [comment]
Closed in PR #71
