### ISSUE TITLE
Atom feed?

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#9]
I can easily enable the [jekyll-feed](https://help.github.com/articles/atom-rss-feeds-for-github-pages/) plugin to enable *Atom* feeds. We already have a fedd in [atom.xml](https://github.com/MDAnalysis/MDAnalysis.github.io/blob/master/atom.xml)` (I think @dotsdl added it), which is advertised (confusingly) as RSS in [_includes/head.html](https://github.com/MDAnalysis/MDAnalysis.github.io/blob/master/_includes/head.html)
```html
  <!-- RSS -->
  <link rel="alternate" type="application/rss+xml" title="RSS" href="/atom.xml">
```

The `jekyll-feed` plugin would create a file `feed.xml` and we add a line `{% feed_meta %}` that expands to
```html
<link type="application/atom+xml" rel="alternate" href="http://www.mdanalysis.org/feed.xml" title="" />
```

Can someone more web 2.0-savy than myself chime in and tell me if we want this in addition to the current one or to replace the current one? I am always in favor of using existing libraries that we don't have to maintain...

**Comment by dotsdl** [comment]
Not really my area; you could always try it and see! As long as it doesn't break what's already working (RSS, I believe), then it can't hurt?

**Comment by kain88-de** [comment]
RSS works fine now btw. But it would be nice if we advertise it with a button.

**Comment by orbeckst** [comment]
Some browsers do this automagically, others don't. 

If you show me an example page (and a button i can borrow) I can add it. 

--
Oliver Beckstein
email: orbeckst@gmail.com


Am Feb 29, 2016 um 2:06 schrieb kain88-de <notifications@github.com>:

**Comment by kain88-de** [comment]
[Button](https://commons.wikimedia.org/wiki/File:Rss-feed.svg)

[example 1](http://gael-varoquaux.info/index.html#posts) upper right corner
[example 2](http://blog.jupyter.org/2016/02/16/jupyterdays-boston-2016/) upper right corner

But for me it would be best next to the Twitter G+ and other social media button. RSS is kind of old-school social media.

**Comment by orbeckst** [comment]
Can you raise an issue to add a battery of social media buttons?

If you include detail, all the better. 

If you add it yourself---even better! (I'm not very "social" ;-))

--
Oliver Beckstein
email: orbeckst@gmail.com


Am Feb 29, 2016 um 7:25 schrieb kain88-de <notifications@github.com>:
